const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let status,session=null,working=false,hasMessages=false,prefsLoaded=false;
let dark=localStorage.getItem('flight-lab-theme')==='dark';function theme(){document.body.classList.toggle('dark',dark);$('#theme').textContent=dark?'Light mode':'Dark mode';}theme();$('#theme').onclick=()=>{dark=!dark;localStorage.setItem('flight-lab-theme',dark?'dark':'light');theme();};
async function request(path,input){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Lab-CSRF':status.csrf},body:JSON.stringify(input)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
function replyMarkup(text){return text.split(/\n\n+/).map((p,i)=>{const lines=p.split('\n');return `<p>${lines.map((line,j)=>j===0&&(i===0||/^[A-C]\. /.test(line))?`<strong>${esc(line)}</strong>`:esc(line)).join('<br>')}</p>`;}).join('');}
function message(speaker,text,kind=''){if(!hasMessages){$('#messages').innerHTML='';hasMessages=true;}$('#messages').insertAdjacentHTML('beforeend',`<div class="message ${kind}"><div class="speaker">${esc(speaker)}</div><div class="bubble">${kind==='user'?esc(text):replyMarkup(text)}</div></div>`);$('#messages').scrollTop=$('#messages').scrollHeight;}
function note(){const mode=$('#mode').value;$('#connection-note').textContent=mode==='replay'?`Recorded data · clock ${status.replay.clock??'not yet available'}. A real ${$('#model').selectedOptions[0].textContent} call interprets each request; flights come from saved staging responses.`:mode==='staging-public'?'Live public staging search · no account login required. Fresh flight inventory; no booking or account access.':status.live.connected?`Live staging connected temporarily · session token expires ${new Date(status.live.expiresAt).toLocaleTimeString()}. Searches only.`:status.live.reason==='expired'?'Staging login expired. Ask Codex to refresh it; recorded mode still works.':'Staging is not connected to this local agent. Ask Codex to connect your signed-in staging tab; recorded mode still works.';}
async function refresh(){try{const r=await fetch('/api/chat/status');if(!r.ok)throw new Error('Local server unavailable.');status=await r.json();$('#preference-profile').textContent=status.preferenceProfile;$('#preference-description').textContent=status.preferenceProfile.includes('development account')?'Saved behind a loopback-only authenticated development API across chats and restarts. This is not the deployed CommonSwyft account service. Explicit trip requests override defaults.':'Saved on this computer across chats and restarts. Not linked to your CommonSwyft account. Explicit trip requests override defaults.';if(!prefsLoaded){fillPreferences(status.preferences);prefsLoaded=true;}note();$('#examples').innerHTML=status.replay.examples.map(x=>`<button type="button">${esc(x)}</button>`).join('');$('#examples').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#message').value=b.textContent;$('#message').focus();});}catch(e){$('#connection-note').textContent=e.message;}}
async function reset(){if(working)return;if(session){await request('/api/chat/close',{id:session.id});session=null;}hasMessages=false;$('#messages').innerHTML='<div class="empty">New conversation. Choose an example or type a request.</div>';$('#inspect').innerHTML='<p class="quiet">Waiting for your first message.</p>';note();}
for(const id of ['#mode','#model','#effort'])$(id).onchange=()=>reset().catch(e=>message('Connection',e.message));$('#reset').onclick=()=>reset().catch(e=>message('Connection',e.message));
$('#composer').onsubmit=async e=>{e.preventDefault();if(working)return;const text=$('#message').value.trim();if(!text)return;working=true;$('#send').disabled=true;$('#reset').disabled=true;$('#mode').disabled=true;$('#model').disabled=true;$('#effort').disabled=true;$('#activity').textContent='Interpreting your request…';
try{await refresh();if(!status)throw new Error('Local connection unavailable.');if(!session){session=await request('/api/chat/start',{mode:$('#mode').value,model:$('#model').value,effort:$('#effort').value});message('Flight agent',session.text);}message('You',text,'user');$('#message').value='';const data=await request('/api/chat/turn',{id:session.id,text});message('Flight agent',data.result.text);if(data.result.proposedPreferences){fillPreferences(data.result.proposedPreferences);$('#preference-note').textContent='Proposed change—not saved. Review and press Save defaults.';}
const usage=data.events.filter(e=>e.type==='model_usage');const tokens=usage.reduce((n,e)=>n+(e.data.usage?.input_tokens??0)+(e.data.usage?.output_tokens??0),0);
$('#inspect').innerHTML=`<p class="badge">${esc(session.mode==='replay'?'Recorded staging':session.mode==='staging-public'?'Public staging search':'Account-linked staging')} · ${esc(data.result.status)} · ${esc(session.label)} ${esc(session.effort)}</p><p>${(data.latencyMs/1000).toFixed(2)} s total · ${tokens.toLocaleString()} tokens · ${usage.length} model calls</p>${data.grounding?`<p class="check-note">${data.grounding.pass?'✓':'×'} ${data.grounding.checks.filter(c=>c.pass).length}/${data.grounding.checks.length} backend checks passed. ${data.grounding.displayedOffers} offers shown.${!data.grounding.displayedOffers?' No offers to verify field-by-field.':''}</p>`:''}<details open><summary>Saved trip</summary><pre>${esc(JSON.stringify(data.state,null,2))}</pre></details>${data.events.map(e=>`<details ${e.type==='tool_call'?'open':''}><summary>${esc({'tool_call':'Proposed action','flight_api':'Flight data request','model_usage':'Model timing and tokens','search_result':'Search outcome','policy_retrieval':'Retrieved policy passages','policy_answer':'Policy answer and sources','policy_failure':'Policy fallback'}[e.type])}</summary><pre>${esc(JSON.stringify(e.data,null,2))}</pre></details>`).join('')}${data.grounding?`<details><summary>Reply compared with backend</summary>${data.grounding.checks.map(c=>`<p>${c.pass?'✓':'×'} ${esc(c.name)}</p>`).join('')}</details>`:''}`;
$('#activity').textContent=`${data.remainingTurns} messages left in this local server run.`;
}catch(error){message('Could not complete request',error.message);$('#activity').textContent='Nothing was booked. You can reconnect or start a new conversation.';}finally{working=false;$('#send').disabled=false;$('#reset').disabled=false;$('#mode').disabled=false;$('#model').disabled=false;$('#effort').disabled=false;$('#message').focus();}};
refresh();setInterval(()=>{if(!working)refresh();},15000);

function fillPreferences(p={}){$('#home-airport').value=p.homeAirport??'';$('#saved-cabin').value=p.cabin??'';$('#saved-nonstop').checked=p.preferNonstop??false;}
$('#policy-examples').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#message').value=b.textContent;$('#message').focus();});
async function saveDefaults(p){if(working)return;try{await request('/api/preferences',{preferences:p});fillPreferences(p);$('#preference-note').textContent='Saved on this computer. Start a new conversation to use these defaults.';}catch(e){$('#preference-note').textContent=e.message;}}
$('#preferences-form').onsubmit=e=>{e.preventDefault();const p={};const airport=$('#home-airport').value.trim().toUpperCase();if(airport)p.homeAirport=airport;const cabin=$('#saved-cabin').value;if(cabin)p.cabin=cabin;if($('#saved-nonstop').checked)p.preferNonstop=true;saveDefaults(p);};
$('#forget-defaults').onclick=()=>saveDefaults({});
