import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { loadEnvFile } from 'node:process';
import { fileURLToPath } from 'node:url';
import { makeStagingAdapter, readStagingToken, STAGING_BASE } from './staging.mjs';
import { SearchConversation, isoToday } from './search.mjs';
import { shiftIso } from './shared.mjs';
import { verifyFlightData } from './verify-flight-data.mjs';

const root = fileURLToPath(new URL('.', import.meta.url));
if (existsSync(root + '.env')) loadEnvFile(root + '.env');
if (!process.argv.includes('--staging')) throw new Error('Pass --staging to submit one flight search to CommonSwyft staging.');
await readStagingToken();
const adapter = makeStagingAdapter({ maxSearches: 1 });
const today = isoToday(process.env.AGENT_TIMEZONE || 'Europe/London');
const date = shiftIso(today, 14);
const conversation = new SearchConversation({ adapter, today: () => today });
const patch = { origin: 'London', destination: 'New York', cabin: 'business', dates: { mode: 'exact', start: date } };
console.log(`One staging search: London → New York, ${date}, business. No model call or booking.`);
const result = await conversation.find(patch);
const snapshot = adapter.snapshots.at(-1);
const requestedQuery = adapter.calls.find(c => c.method === 'POST')?.body;
const verification = snapshot ? verifyFlightData(result, snapshot, requestedQuery) : { pass: false, checks: [{ name: 'No validated API snapshot received', pass: false }], displayedOffers: 0 };
const report = { executedAt: new Date().toISOString(), apiBase: STAGING_BASE, dataMode: 'staging', model: null, input: patch, calls: adapter.calls, result, verification, snapshot: snapshot ?? null };
const path = root + 'eval-results/staging-' + new Date().toISOString().replaceAll(':', '-') + '.json';
mkdirSync(root + 'eval-results', { recursive: true });
writeFileSync(path, JSON.stringify(report, null, 2), { mode: 0o600 });
console.log(result.text);
console.log(`\nData checks: ${verification.pass ? 'PASS' : 'FAIL'}; ${verification.displayedOffers} displayed offers. Report: ${path}`);
if (verification.displayedOffers === 0) console.log('No displayed offers: price/flight-field fidelity is not established by this run.');
process.exitCode = verification.pass ? 0 : 1;
